/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    IdentityRegistry: {
      address: "0x700b6a60ce7eaaea56f065753d8dcb9653dbad35",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getIdentity",
          inputs: [
            {
              name: "linkageHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "wallet",
              type: "address",
              internalType: "address",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "exists",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "registerIdentity",
          inputs: [
            {
              name: "linkageHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "privyWallet",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "created",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "verifyIdentity",
          inputs: [
            {
              name: "linkageHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "walletLinkageHashes",
          inputs: [
            {
              name: "wallet",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "linkageHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "IdentityBound",
          inputs: [
            {
              name: "linkageHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "privyWallet",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "EmptyLinkageHash",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptyWallet",
          inputs: [],
        },
        {
          type: "error",
          name: "IdentityAlreadyBound",
          inputs: [
            {
              name: "linkageHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 1,
    },
    DocumentRegistry: {
      address: "0xa15bb66138824a1c7167f5e85b957d04dd34e468",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getDocument",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "ownerWallet",
              type: "address",
              internalType: "address",
            },
            {
              name: "ipfsCid",
              type: "string",
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "exists",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getDocumentByHashAt",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "index",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "documentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "ownerWallet",
              type: "address",
              internalType: "address",
            },
            {
              name: "ipfsCid",
              type: "string",
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getDocumentCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getDocumentCountByHash",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getDocumentRecord",
          inputs: [
            {
              name: "documentId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "ownerWallet",
              type: "address",
              internalType: "address",
            },
            {
              name: "ipfsCid",
              type: "string",
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "registerDocument",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "ownerWallet",
              type: "address",
              internalType: "address",
            },
            {
              name: "ipfsCid",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "documentId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "DocumentRegistered",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "documentId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "ipfsCid",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "DocumentIndexOutOfBounds",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "index",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "EmptyDocumentHash",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptyIpfsCid",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptyOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 2,
    },
    SignatureLog: {
      address: "0xb19b36b1456e65e3a6d514d3f715f204bd59f431",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getDocumentSignatureAt",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "index",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getDocumentSignatureCount",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getSignature",
          inputs: [
            {
              name: "sigHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "payloadHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "previousSigHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "signerHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "exists",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "logDelegation",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "fromHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "toHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "logSignature",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "payloadHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "sigHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "previousSigHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "signerHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "created",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "DocumentSigned",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "signerHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "sigHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "payloadHash",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "previousSigHash",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SigningDelegated",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "fromHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "toHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "EmptyDocumentHash",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptySignatureHash",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptySignerHash",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "SignatureAlreadyLogged",
          inputs: [
            {
              name: "sigHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 2,
    },
    WorkflowTracker: {
      address: "0x8ce361602b935680e8dec218b820ff5056beb7af",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "advanceStep",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "step",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createWorkflow",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "created",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "finalizeDocument",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "verificationUrl",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getWorkflow",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "currentStep",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "status",
              type: "uint8",
              internalType: "enum WorkflowTracker.WorkflowStatus",
            },
            {
              name: "verificationUrl",
              type: "string",
              internalType: "string",
            },
            {
              name: "updatedAt",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "exists",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "markResubmitted",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "rejectWorkflow",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
            {
              name: "reason",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "DocumentFinalized",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "verificationUrl",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WorkflowCreated",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WorkflowRejected",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "approver",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "reason",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WorkflowStepCompleted",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "step",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
            {
              name: "approver",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "EmptyApprover",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptyDocumentHash",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "WorkflowMissing",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 2,
    },
  },
  11155111: {
    IdentityRegistry: {
      address: "0x9adc1445e1814ee1f68a973db24708c35f68aa77",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getIdentity",
          inputs: [
            {
              name: "linkageHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "wallet",
              type: "address",
              internalType: "address",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "exists",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "registerIdentity",
          inputs: [
            {
              name: "linkageHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "privyWallet",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "created",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "verifyIdentity",
          inputs: [
            {
              name: "linkageHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "walletLinkageHashes",
          inputs: [
            {
              name: "wallet",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "linkageHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "IdentityBound",
          inputs: [
            {
              name: "linkageHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "privyWallet",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "EmptyLinkageHash",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptyWallet",
          inputs: [],
        },
        {
          type: "error",
          name: "IdentityAlreadyBound",
          inputs: [
            {
              name: "linkageHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 10865716,
    },
    DocumentRegistry: {
      address: "0xc4c9a15ecf1c8086241a72f4a21f7414f8236dbf",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getDocument",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "ownerWallet",
              type: "address",
              internalType: "address",
            },
            {
              name: "ipfsCid",
              type: "string",
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "exists",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getDocumentByHashAt",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "index",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "documentId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "ownerWallet",
              type: "address",
              internalType: "address",
            },
            {
              name: "ipfsCid",
              type: "string",
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getDocumentCount",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getDocumentCountByHash",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getDocumentRecord",
          inputs: [
            {
              name: "documentId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "ownerWallet",
              type: "address",
              internalType: "address",
            },
            {
              name: "ipfsCid",
              type: "string",
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "registerDocument",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "ownerWallet",
              type: "address",
              internalType: "address",
            },
            {
              name: "ipfsCid",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "documentId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "DocumentRegistered",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "documentId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "ipfsCid",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "DocumentIndexOutOfBounds",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "index",
              type: "uint256",
              internalType: "uint256",
            },
          ],
        },
        {
          type: "error",
          name: "EmptyDocumentHash",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptyIpfsCid",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptyOwner",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 10865716,
    },
    SignatureLog: {
      address: "0x688cc080cdc6a8d291d671baa8047abef087d188",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getDocumentSignatureAt",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "index",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getDocumentSignatureCount",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getSignature",
          inputs: [
            {
              name: "sigHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "payloadHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "previousSigHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "signerHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "timestamp",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "exists",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "logDelegation",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "fromHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "toHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "logSignature",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "payloadHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "sigHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "previousSigHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "signerHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "created",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "DocumentSigned",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "signerHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "sigHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "payloadHash",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "previousSigHash",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SigningDelegated",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "fromHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "toHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "EmptyDocumentHash",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptySignatureHash",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptySignerHash",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "SignatureAlreadyLogged",
          inputs: [
            {
              name: "sigHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 10865716,
    },
    WorkflowTracker: {
      address: "0x965f3bff76582be13bdd8b766431643530a510aa",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "advanceStep",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "step",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createWorkflow",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "created",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "finalizeDocument",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "verificationUrl",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getWorkflow",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [
            {
              name: "currentStep",
              type: "uint8",
              internalType: "uint8",
            },
            {
              name: "status",
              type: "uint8",
              internalType: "enum WorkflowTracker.WorkflowStatus",
            },
            {
              name: "verificationUrl",
              type: "string",
              internalType: "string",
            },
            {
              name: "updatedAt",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "exists",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "markResubmitted",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "rejectWorkflow",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "approver",
              type: "address",
              internalType: "address",
            },
            {
              name: "reason",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "DocumentFinalized",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "verificationUrl",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WorkflowCreated",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WorkflowRejected",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "approver",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "reason",
              type: "string",
              indexed: false,
              internalType: "string",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "WorkflowStepCompleted",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "step",
              type: "uint8",
              indexed: false,
              internalType: "uint8",
            },
            {
              name: "approver",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "EmptyApprover",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptyDocumentHash",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "WorkflowMissing",
          inputs: [
            {
              name: "docHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 10865716,
    },
    AgencyRegistry: {
      address: "0xa669f97db5856ee02160193a578f7c4faa24a919",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "logAgencyAdminRegistered",
          inputs: [
            {
              name: "agencyId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "adminWalletHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "logAgencyEnrolled",
          inputs: [
            {
              name: "agencyId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "nameHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "logAgencyOfficerRegistered",
          inputs: [
            {
              name: "agencyId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "officerWalletHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "logAgencyServiceCreated",
          inputs: [
            {
              name: "agencyId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "serviceId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "serviceNameHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "logAgencyWorkflowConfigured",
          inputs: [
            {
              name: "agencyId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "serviceId",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "workflowHash",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "AgencyAdminRegistered",
          inputs: [
            {
              name: "agencyId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "adminWalletHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "AgencyEnrolled",
          inputs: [
            {
              name: "agencyId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "nameHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "AgencyOfficerRegistered",
          inputs: [
            {
              name: "agencyId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "officerWalletHash",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "AgencyServiceCreated",
          inputs: [
            {
              name: "agencyId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "serviceId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "serviceNameHash",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "AgencyWorkflowConfigured",
          inputs: [
            {
              name: "agencyId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "serviceId",
              type: "bytes32",
              indexed: true,
              internalType: "bytes32",
            },
            {
              name: "workflowHash",
              type: "bytes32",
              indexed: false,
              internalType: "bytes32",
            },
            {
              name: "timestamp",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "EmptyAgencyId",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptyMemberHash",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptyNameHash",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptyServiceId",
          inputs: [],
        },
        {
          type: "error",
          name: "EmptyWorkflowHash",
          inputs: [],
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 10865716,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
